version: '3'
services:
    server:
        build: server
        ports:
            - 8000:8000
        command: python ./app.py
        depends_on:
            - database
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_HOST: ${POSTGRES_HOST}
            POSTGRES_PORT: ${POSTGRES_PORT}

    liquibase:
        image: "webdevops/liquibase:postgres"
        volumes:
            - .:/liquibase
        environment:
            - LIQUIBASE_CHANGELOG=changelog.xml
            - LIQUIBASE_URL=jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
            - LIQUIBASE_USERNAME=${POSTGRES_USER}
            - LIQUIBASE_PASSWORD=${POSTGRES_PASSWORD}

    database:
        image: ${POSTGRES_VERSION}
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - ${POSTGRES_PORT}:${POSTGRES_PORT}

    camunda:
        image: camunda/camunda-bpm-platform:latest
        ports:
            - "8085:8080"
